language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "Tkf1mZKy6PLeNCC7YHuq9lC+m3U8YfsGsppWzuE8kQt96lxTBO4UUSQSv4SGJaNjrlPQ181qJj8BvyPvINxCjFWq1uT4XTeK/IwFN2mhmCcpNYoHAkuXD3C3MHz3PTC/bH1p7MFG19hc7UPdbPzni6O+1TcnmX6q0v7LNrDfotyJj6yJZatpjDDwEGpvIifGZdLz2oX73PBHcmXRduci08syDQc3Y6NCSZMy2J1Ixz3uavbCIyBoOzkY/9D9DLrXZhUvHGDSlHy25DzObqHmk3dtXHbydemKKuLexd410rNE+5M2IqQUyjQwhb590pUZXMCEOUTGo1HA4jcLXBuFK9QMN3ednM62lJZOfpi0+nHk+7VGUJmCOujBDC/OMN3QUF/KRNQmftsjBMZJekbMVyUXcsJgwXkGMV5uriAqioX94Vc5geYD65HCxvPLkf4A8LGOhRwgAWhm3oE23cre7U3FsZSiVx7JFB3Lr0GTWVsdmo1bNv41EfScgv+6JVK0nn6Etxp/JKDl9pAIXjtJVTBYfFbl3fEdUCnIlrO7R6HqCJIxkY09PesYcUOKODq1udhqKrSjydIs8pfMliFXADuD43ULInA88y9xcLwcUCuVIaU4hd62WZHEbZe+iDeJOVeQmP7cMVDLcMhDKncyfjG508uAa6KQuGhx4VybvEU="
