language: node_js
node_js:
- '8'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- cat .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install
script:
- npm run pr
- "./ci/shim.js"
- "./ci/doc.js"
- "./ci/test.js"
after_success:
- publish-if-needed
env:
  global:
  - secure: KkERHt9lK/jBNM43mJ4keTH/KD+qngXam3wDfQnzfOpjCtDzoXqf3Q63scfGleLnVMaTOR6V7HbimNoRI0LTsp8iuN3l75iX3HoxTArqOQAjCQY6enCT+MpRsQdZwKYIpXk5XbFd/MLRIBgDj872E7focrzVMkWm2zoOuRzAyWMkpch4HpDubZ40CDdfWIdPo0DoNY4jZLl+IQfRPP+x0CUQ/UI6iCXPhTRLJ4yNGu709l2Dd4SJKJWow/szfBQgfWmsEHZSegNzkvhq/3yxUIV9JtmSPhCebZ2SkR2XeYHsQsi4hZ3WPT86e57VFpAoQUfAoOtDOEXtxU7wU+GwiHtIwzNWQJtLnWjqvWn8RkDqfCtQ6Fid9pnEhs1CrOd14GgcNw5QJdosUeZwtQPeXvZn0INvOGK+WxrrHXHekCGOmub7m2FFjm9m190tag4VQWV0RlSNUFKRcJjulED16+Y+BOlBUc2g9kor/IUQKwppnaVJNzY2dIhjVUHqa6heeC6k4mJon3qsVE6UVxIBi0RG8mCgZRfh9WirVFgkda/OEVL/KkRzIOudgbeg6BqXSDI7iSgnBIMKxknD1s6ETnGB8HatD1NkM+yyoqzhuWnZCo9UQrqS31ebpqjkaZdlAp6n3rYFAOpLi9n99/JkSPYAy9AH4nwSmw/P/bl0LjI=
